# Generated by Django 4.2.23 on 2025-09-28 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='کل بازدیدها')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='بازدیدکنندگان منحصر به فرد')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='کاربران جدید')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='بازدید صفحات')),
                ('avg_session_duration', models.DurationField(blank=True, null=True, verbose_name='میانگین مدت جلسه')),
                ('bounce_rate', models.FloatField(default=0, verbose_name='نرخ پرش')),
            ],
            options={
                'verbose_name': 'آمار سایت',
                'verbose_name_plural': 'آمارهای سایت',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default='TEMP-TICKET', max_length=50, unique=True, verbose_name='شناسه تیکت'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.CreateModel(
            name='StoreAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0, verbose_name='امتیاز کلی')),
                ('layout_score', models.FloatField(default=0, verbose_name='امتیاز چیدمان')),
                ('lighting_score', models.FloatField(default=0, verbose_name='امتیاز نورپردازی')),
                ('color_score', models.FloatField(default=0, verbose_name='امتیاز رنگ\u200cبندی')),
                ('signage_score', models.FloatField(default=0, verbose_name='امتیاز تابلوها')),
                ('layout_recommendations', models.TextField(blank=True, verbose_name='توصیه\u200cهای چیدمان')),
                ('lighting_recommendations', models.TextField(blank=True, verbose_name='توصیه\u200cهای نورپردازی')),
                ('color_recommendations', models.TextField(blank=True, verbose_name='توصیه\u200cهای رنگ\u200cبندی')),
                ('signage_recommendations', models.TextField(blank=True, verbose_name='توصیه\u200cهای تابلوها')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='فایل گزارش')),
                ('images_analysis', models.JSONField(default=list, verbose_name='تحلیل تصاویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('store_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.storeanalysis', verbose_name='تحلیل فروشگاه')),
            ],
            options={
                'verbose_name': 'نتیجه تحلیل فروشگاه',
                'verbose_name_plural': 'نتایج تحلیل فروشگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تخفیف')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('max_uses', models.PositiveIntegerField(default=100, verbose_name='حداکثر استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حداقل مبلغ سفارش')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='اعتبار از')),
                ('valid_until', models.DateTimeField(verbose_name='اعتبار تا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='store_analy_code_90e10e_idx'), models.Index(fields=['is_active'], name='store_analy_is_acti_b193cb_idx'), models.Index(fields=['valid_from'], name='store_analy_valid_f_e4d331_idx'), models.Index(fields=['valid_until'], name='store_analy_valid_u_34885d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوای پیام')),
                ('is_admin_reply', models.BooleanField(default=False, verbose_name='پاسخ ادمین')),
                ('attachments', models.JSONField(default=list, verbose_name='پیوست\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store_analysis.supportticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket'], name='store_analy_ticket__f1be30_idx'), models.Index(fields=['sender'], name='store_analy_sender__a72b55_idx'), models.Index(fields=['created_at'], name='store_analy_created_84152c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('store_type', models.CharField(choices=[('supermarket', 'سوپرمارکت'), ('convenience_store', 'فروشگاه کوچک'), ('department_store', 'فروشگاه بزرگ'), ('specialty_store', 'فروشگاه تخصصی'), ('pharmacy', 'داروخانه'), ('bookstore', 'کتابفروشی'), ('electronics', 'لوازم الکترونیکی'), ('clothing', 'پوشاک'), ('food', 'مواد غذایی'), ('other', 'سایر')], max_length=20, verbose_name='نوع فروشگاه')),
                ('store_location', models.CharField(max_length=300, verbose_name='موقعیت فروشگاه')),
                ('area', models.CharField(max_length=100, verbose_name='منطقه')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('store_size', models.PositiveIntegerField(verbose_name='مساحت فروشگاه (متر مربع)')),
                ('employee_count', models.PositiveIntegerField(default=1, verbose_name='تعداد کارکنان')),
                ('opening_hours', models.CharField(blank=True, max_length=200, verbose_name='ساعات کاری')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال تاسیس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاعات پایه فروشگاه',
                'verbose_name_plural': 'اطلاعات پایه فروشگاه\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='store_analy_user_id_c34278_idx'), models.Index(fields=['store_type'], name='store_analy_store_t_78e77f_idx'), models.Index(fields=['city'], name='store_analy_city_c034eb_idx'), models.Index(fields=['created_at'], name='store_analy_created_0f2019_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(verbose_name='آدرس صفحه')),
                ('page_title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='صفحه مرجع')),
                ('session_id', models.CharField(max_length=100, verbose_name='شناسه جلسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازدید')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید صفحه',
                'verbose_name_plural': 'بازدیدهای صفحات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page_url'], name='store_analy_page_ur_ab76b5_idx'), models.Index(fields=['created_at'], name='store_analy_created_0b9e65_idx'), models.Index(fields=['user'], name='store_analy_user_id_c92766_idx'), models.Index(fields=['session_id'], name='store_analy_session_49fb1a_idx')],
            },
        ),
    ]
