# Generated by Django 4.2.23 on 2025-09-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0031_alter_faqservice_sort_order_and_more'),
        ('store_analysis', '0032_align_payment_pk_and_wallet_tx'),
    ]

    operations = [
    ]
