# Generated by Django 4.2.23 on 2025-09-29 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0033_merge_20250930_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_analysis.payment', verbose_name='پرداخت'),
        ),
    ]
