# Generated by Django 4.2.23 on 2025-09-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0034_alter_wallettransaction_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='tags',
            field=models.JSONField(default=list, verbose_name='برچسب\u200cها'),
        ),
    ]
