# Generated by Django 4.2.23 on 2025-09-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0035_add_tags_to_supportticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqservice',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='analysis_result',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='store_description',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='is_admin_reply',
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
