# Generated by Django 4.2.23 on 2025-10-01 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0040_storeanalysis_results_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('store_type', models.CharField(blank=True, max_length=50, verbose_name='نوع فروشگاه')),
                ('contact_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('additional_notes', models.TextField(blank=True, verbose_name='توضیحات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_analysis.storeanalysis', verbose_name='تحلیل مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دفتر تلفن',
                'verbose_name_plural': 'دفتر تلفن\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_name'], name='store_analy_store_n_253694_idx'), models.Index(fields=['contact_email'], name='store_analy_contact_8ddee6_idx'), models.Index(fields=['contact_phone'], name='store_analy_contact_636f80_idx'), models.Index(fields=['user'], name='store_analy_user_id_6ac192_idx'), models.Index(fields=['created_at'], name='store_analy_created_0e3f00_idx')],
            },
        ),
    ]
