# Generated by Django 4.2.23 on 2025-10-04 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0042_promotionalbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 14, 55, 9, 492275, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
