# Generated by Django 4.2.23 on 2025-10-06 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0046_fix_django_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 22, 13, 44, 496731, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
