# Generated by Django 4.2.23 on 2025-10-08 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0053_order_payment_method_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 22, 54, 39, 317735, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
