# Generated by Django 4.2.23 on 2025-10-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0059_add_usersubscription'),
    ]

    # This migration previously attempted to create UserSubscription, but the model
    # is already created in the initial migration. Keep this migration empty to
    # avoid duplicate table creation.
    operations = []
