# Generated by Django 4.2.23 on 2025-10-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0060_fix_usersubscription_table'),
    ]

    # This migration is intentionally left empty because UserSubscription model
    # is created in migration 0060. Keeping this file to preserve migration history.
    operations = []
