# Generated by Django 4.2.23 on 2025-10-09 22:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0061_create_usersubscription_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'اشتراک کاربر', 'verbose_name_plural': 'اشتراک\u200cهای کاربران'},
        ),
        # Removed: previous migration attempted to remove 'service_package' field,
        # but current model uses 'package'. Skip RemoveField to keep state consistent.
        migrations.AddField(
            model_name='usersubscription',
            name='analyses_used',
            field=models.PositiveIntegerField(default=0, verbose_name='تحلیل\u200cهای استفاده شده'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='max_analyses',
            field=models.PositiveIntegerField(default=10, verbose_name='حداکثر تحلیل'),
        ),
        # 'package' and 'payment' fields already exist on the initial model.
        # Skipping AddField for 'package' and 'payment' to avoid duplicate columns.
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 8, 22, 41, 5, 107069, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        # Indexes on usersubscription already created in initial migration; skip to avoid duplicates.
    ]
