# Generated by Django 4.2.23 on 2025-10-10 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0065_alter_promotionalbanner_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('discount_type', models.CharField(choices=[('opening', 'تخفیف افتتاحیه'), ('seasonal', 'تخفیف فصلی'), ('nowruz', 'تخفیف نوروزی'), ('special', 'تخفیف ویژه')], default='opening', max_length=50, verbose_name='نوع تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
                'ordering': ['key'],
            },
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 19, 59, 14, 51740, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
