# Generated by Django 4.2.23 on 2025-10-10 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0067_systemsettings_alter_discountnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 20, 12, 37, 436788, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
