# Generated by Django 4.2.23 on 2025-10-11 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0068_alter_promotionalbanner_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 6, 17, 22, 33317, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
