# Generated by Django 4.2.23 on 2025-10-11 10:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0069_alter_promotionalbanner_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionalbanner',
            options={'verbose_name': 'بنر تبلیغاتی', 'verbose_name_plural': 'بنرهای تبلیغاتی'},
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 10, 39, 46, 867780, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='مشاوره جدید', max_length=200, verbose_name='عنوان جلسه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('store_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='store_analysis.storeanalysis', verbose_name='تحلیل فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جلسه چت',
                'verbose_name_plural': 'جلسات چت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار هوشمند'), ('system', 'سیستم')], max_length=20, verbose_name='نقش')),
                ('content', models.TextField(verbose_name='محتوای پیام')),
                ('ai_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل AI')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='زمان پردازش (ثانیه)')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='تعداد توکن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store_analysis.chatsession', verbose_name='جلسه چت')),
            ],
            options={
                'verbose_name': 'پیام چت',
                'verbose_name_plural': 'پیام\u200cهای چت',
                'ordering': ['created_at'],
            },
        ),
    ]
