# Generated by Django 4.2.23 on 2025-10-11 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0070_alter_promotionalbanner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='حساب پریمیوم'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای پریمیوم'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 20, 11, 19, 310787, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
