# Generated by Django 4.2.23 on 2025-10-16 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0077_add_message_type_to_ticketmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 22, 38, 33, 323035, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
