# Generated by Django 4.2.23 on 2025-10-17 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0080_fix_missing_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 19, 54, 38, 804890, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
