# Generated by Django 4.2.23 on 2025-10-17 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0081_add_missing_fields_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 19, 59, 6, 321270, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
