# Generated by Django 4.2.23 on 2025-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0082_add_critical_missing_fields'),
    ]

    operations = [
        # authority field already added in an earlier migration (0076); skip here.
        
        # اضافه کردن فیلد employee_count به StoreBasicInfo
        migrations.AddField(
            model_name='storebasicinfo',
            name='employee_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد کارکنان'),
        ),
        
        # اضافه کردن فیلد lighting_score به StoreAnalysisResult
        migrations.AddField(
            model_name='storeanalysisresult',
            name='lighting_score',
            field=models.FloatField(default=0, verbose_name='امتیاز نورپردازی'),
        ),
    ]
