# Generated by Django 4.2.23 on 2025-10-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0083_fix_critical_fields_manual'),
    ]

    def create_indexes(apps, schema_editor):
        if schema_editor.connection.vendor == 'postgresql':
            sql = """
            CREATE INDEX IF NOT EXISTS idx_storeanalysis_user_status 
            ON store_analysis_storeanalysis (user_id, status);
            
            CREATE INDEX IF NOT EXISTS idx_storeanalysis_created 
            ON store_analysis_storeanalysis (created_at);
            
            CREATE INDEX IF NOT EXISTS idx_storeanalysis_priority 
            ON store_analysis_storeanalysis (priority);
            
            CREATE INDEX IF NOT EXISTS idx_payment_authority 
            ON store_analysis_payment (authority);
            
            CREATE INDEX IF NOT EXISTS idx_payment_status 
            ON store_analysis_payment (status);
            
            CREATE INDEX IF NOT EXISTS idx_order_user 
            ON store_analysis_order (user_id);
            
            CREATE INDEX IF NOT EXISTS idx_supportticket_status 
            ON store_analysis_supportticket (status);
            
            CREATE INDEX IF NOT EXISTS idx_ticketmessage_ticket 
            ON store_analysis_ticketmessage (ticket_id);
            
            CREATE INDEX IF NOT EXISTS idx_userprofile_user 
            ON store_analysis_userprofile (user_id);
            """
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(sql)

    operations = [
        migrations.RunPython(create_indexes, migrations.RunPython.noop),
    ]
