# Generated by Django 4.2.23 on 2025-10-17 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0086_add_analysis_id_to_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 20, 54, 56, 966594, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
