# Generated by Django 4.2.23 on 2025-10-19 19:55

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0097_safe_fk_migration_expand_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 18, 19, 55, 6, 14205, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
