# Generated by Django 4.2.23 on 2025-10-19 21:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0098_alter_order_id_alter_promotionalbanner_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrequest',
            name='order',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='order',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='store_analysis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_analysis.storeanalysis', verbose_name='تحلیل فروشگاه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='اطلاعات اضافی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='business_goals',
            field=models.TextField(blank=True, verbose_name='اهداف کسب\u200cوکار'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل تماس'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ نهایی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='marketing_budget',
            field=models.CharField(blank=True, max_length=50, verbose_name='بودجه بازاریابی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='package_type',
            field=models.CharField(default='basic', max_length=20, verbose_name='نوع پکیج'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_address',
            field=models.TextField(blank=True, verbose_name='آدرس فروشگاه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='اندازه فروشگاه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع فروشگاه'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 18, 21, 13, 4, 785130, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
