# Generated by Django 4.2.23 on 2025-10-22 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0107_alter_promotionalbanner_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 21, 6, 11, 5, 153756, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
