# Generated by Django 4.2.23 on 2025-10-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0108_add_faq_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
