# Generated by Django 4.2.23 on 2025-10-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0109_add_faq_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeanalysis',
            name='package_type',
            field=models.CharField(default='basic', max_length=20, verbose_name='نوع پکیج'),
        ),
    ]
