# Generated by Django 4.2.23 on 2025-10-22 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0110_add_package_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 21, 7, 47, 52, 944834, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
