# Generated by Django 4.2.23 on 2025-11-01 04:37

from django.db import migrations, models
import store_analysis.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0113_order_base_amount_order_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=store_analysis.models.default_banner_end_date, verbose_name='تاریخ پایان'),
        ),
    ]
