# Generated by Django 4.2.23 on 2025-11-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0118_ticketmessage_is_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeanalysis',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='contact_phone',
        ),
    ]
