# Generated by Django 4.2.23 on 2025-11-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0119_remove_storeanalysis_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP کلاینت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='موقعیت کلاینت'),
        ),
    ]
