# Generated by Django 4.2.23 on 2025-09-25 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='کلمه کلیدی')),
                ('search_volume', models.PositiveIntegerField(default=0, verbose_name='حجم جستجو')),
                ('difficulty', models.PositiveIntegerField(default=0, verbose_name='سختی')),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه کلیک')),
                ('target_url', models.URLField(blank=True, null=True, verbose_name='URL هدف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کلمه کلیدی SEO',
                'verbose_name_plural': 'کلمات کلیدی SEO',
                'ordering': ['-search_volume'],
            },
        ),
        migrations.CreateModel(
            name='SEOMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('organic_traffic', models.PositiveIntegerField(default=0, verbose_name='ترافیک ارگانیک')),
                ('keyword_rankings', models.PositiveIntegerField(default=0, verbose_name='رتبه\u200cبندی کلمات کلیدی')),
                ('backlinks_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بک\u200cلینک')),
                ('domain_authority', models.PositiveIntegerField(default=0, verbose_name='اعتبار دامنه')),
                ('page_speed_score', models.PositiveIntegerField(default=0, verbose_name='امتیاز سرعت صفحه')),
            ],
            options={
                'verbose_name': 'متریک SEO',
                'verbose_name_plural': 'متریک\u200cهای SEO',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=200, verbose_name='URL مبدأ')),
                ('target_url', models.CharField(max_length=200, verbose_name='URL مقصد')),
                ('anchor_text', models.CharField(max_length=100, verbose_name='متن لنگر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'لینک داخلی',
                'verbose_name_plural': 'لینک\u200cهای داخلی',
                'unique_together': {('source_url', 'target_url', 'anchor_text')},
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(verbose_name='محتوای کامل')),
                ('excerpt', models.TextField(max_length=500, verbose_name='خلاصه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='تصویر شاخص')),
                ('meta_description', models.CharField(max_length=160, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='کلمات کلیدی')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله وبلاگ',
                'verbose_name_plural': 'مقالات وبلاگ',
                'ordering': ['-created_at'],
            },
        ),
    ]
