# Generated by Django 5.2.1 on 2025-06-07 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('layout_image', models.ImageField(blank=True, null=True, upload_to='layouts/', verbose_name='تصویر چیدمان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('results', models.JSONField(blank=True, null=True, verbose_name='نتایج')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تحلیل فروشگاه',
                'verbose_name_plural': 'تحلیل\u200cهای فروشگاه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetailedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_analysis', models.JSONField(verbose_name='تحلیل ترافیک')),
                ('layout_analysis', models.JSONField(verbose_name='تحلیل چیدمان')),
                ('customer_behavior', models.JSONField(verbose_name='رفتار مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('store_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_analysis_data', to='store_analysis.storeanalysis', verbose_name='تحلیل فروشگاه')),
            ],
            options={
                'verbose_name': 'تحلیل تکمیلی',
                'verbose_name_plural': 'تحلیل\u200cهای تکمیلی',
            },
        ),
    ]
