# Generated by Django 5.2.1 on 2025-06-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeanalysis',
            name='avg_customer_time',
            field=models.IntegerField(default=0, verbose_name='میانگین زمان حضور مشتری'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='checkout_location',
            field=models.CharField(default='front', max_length=100, verbose_name='محل صندوق'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='color_temperature',
            field=models.IntegerField(default=0, verbose_name='دمای رنگ'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='customer_traffic',
            field=models.CharField(default='low', max_length=100, verbose_name='ترافیک مشتری'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='customer_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع مشتری'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='lighting_intensity',
            field=models.IntegerField(default=0, verbose_name='شدت نور'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='main_entrance',
            field=models.CharField(default='front', max_length=100, verbose_name='ورودی اصلی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='main_lighting',
            field=models.CharField(default='artificial', max_length=100, verbose_name='نورپردازی اصلی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='تلفن'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='product_categories',
            field=models.TextField(blank=True, null=True, verbose_name='دسته\u200cبندی محصولات'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='product_placement',
            field=models.TextField(blank=True, null=True, verbose_name='چیدمان محصولات'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='special_areas',
            field=models.TextField(blank=True, null=True, verbose_name='مناطق ویژه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_size',
            field=models.FloatField(default=0, verbose_name='متراژ'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_type',
            field=models.CharField(default='retail', max_length=100, verbose_name='نوع فروشگاه'),
        ),
    ]
