# Generated by Django 4.2.23 on 2025-09-27 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='واحد پول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف\u200cهای پول',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('technical', 'فنی'), ('billing', 'صورت\u200cحساب'), ('general', 'عمومی'), ('feature_request', 'درخواست ویژگی'), ('bug_report', 'گزارش باگ')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('resolved', 'حل شده'), ('closed', 'بسته')], default='open', max_length=20, verbose_name='وضعیت')),
                ('attachments', models.JSONField(default=list, verbose_name='پیوست\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حل')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('store_url', models.URLField(verbose_name='آدرس فروشگاه')),
                ('store_description', models.TextField(blank=True, verbose_name='توضیحات فروشگاه')),
                ('analysis_type', models.CharField(choices=[('basic', 'پایه'), ('professional', 'حرفه\u200cای'), ('advanced', 'پیشرفته'), ('custom', 'سفارشی')], default='basic', max_length=20, verbose_name='نوع تحلیل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('analysis_result', models.JSONField(blank=True, null=True, verbose_name='نتیجه تحلیل')),
                ('ai_insights', models.TextField(blank=True, verbose_name='بینش\u200cهای هوش مصنوعی')),
                ('recommendations', models.TextField(blank=True, verbose_name='توصیه\u200cها')),
                ('store_images', models.JSONField(default=list, verbose_name='تصاویر فروشگاه')),
                ('analysis_files', models.JSONField(default=list, verbose_name='فایل\u200cهای تحلیل')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='واحد پول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تحلیل فروشگاه',
                'verbose_name_plural': 'تحلیل\u200cهای فروشگاه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('technical', 'فنی'), ('billing', 'صورت\u200cحساب'), ('features', 'ویژگی\u200cها'), ('troubleshooting', 'عیب\u200cیابی')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('keywords', models.TextField(blank=True, verbose_name='کلمات کلیدی')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['sort_order', 'category', 'question'],
                'indexes': [models.Index(fields=['category'], name='store_analy_categor_10ab89_idx'), models.Index(fields=['is_active'], name='store_analy_is_acti_e154af_idx'), models.Index(fields=['is_featured'], name='store_analy_is_feat_4e314a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdrawal', 'برداشت'), ('payment', 'پرداخت'), ('refund', 'برگشت'), ('bonus', 'پاداش')], max_length=20, verbose_name='نوع تراکنش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='موجودی پس از تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_analysis.payment', verbose_name='پرداخت')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store_analysis.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet'], name='store_analy_wallet__b93b5f_idx'), models.Index(fields=['transaction_type'], name='store_analy_transac_2b48d8_idx'), models.Index(fields=['created_at'], name='store_analy_created_1b24b0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='store_analy_user_id_03b95e_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user'], name='store_analy_user_id_6484ec_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='store_analy_status_df01c6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category'], name='store_analy_categor_59e1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority'], name='store_analy_priorit_133245_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to'], name='store_analy_assigne_599220_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_at'], name='store_analy_created_e6b30c_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['user'], name='store_analy_user_id_4ddf34_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['status'], name='store_analy_status_87f309_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['analysis_type'], name='store_analy_analysi_048c92_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['created_at'], name='store_analy_created_66b632_idx'),
        ),
    ]
