# Generated by Django 5.2.1 on 2025-06-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0002_storeanalysis_avg_customer_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeanalysis',
            name='checkout_location',
            field=models.CharField(choices=[('front', 'جلوی فروشگاه'), ('side', 'کنار فروشگاه'), ('back', 'پشت فروشگاه'), ('multiple', 'چند ورودی')], default='front', max_length=100, verbose_name='محل صندوق'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='customer_traffic',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('very_high', 'خیلی زیاد')], default='low', max_length=100, verbose_name='ترافیک مشتری'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='main_entrance',
            field=models.CharField(choices=[('front', 'جلوی فروشگاه'), ('side', 'کنار فروشگاه'), ('back', 'پشت فروشگاه'), ('multiple', 'چند ورودی')], default='front', max_length=100, verbose_name='ورودی اصلی'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='main_lighting',
            field=models.CharField(choices=[('natural', 'طبیعی'), ('artificial', 'مصنوعی'), ('mixed', 'ترکیبی')], default='artificial', max_length=100, verbose_name='نورپردازی اصلی'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='product_categories',
            field=models.JSONField(default=list, verbose_name='دسته\u200cبندی محصولات'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='store_type',
            field=models.CharField(choices=[('supermarket', 'سوپرمارکت'), ('hypermarket', 'هایپرمارکت'), ('chain', 'فروشگاه زنجیره\u200cای'), ('clothing', 'پوشاک'), ('appliance', 'لوازم خانگی'), ('other', 'سایر')], default='supermarket', max_length=100, verbose_name='نوع فروشگاه'),
        ),
    ]
