# Generated by Django 4.2.23 on 2025-09-27 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0002_wallet_supportticket_storeanalysis_faqservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('refunded', 'برگشت شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ پایه')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ نهایی')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='واحد پول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_analysis.payment', verbose_name='پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='store_analy_user_id_88d4e0_idx'), models.Index(fields=['status'], name='store_analy_status_5912ec_idx'), models.Index(fields=['order_number'], name='store_analy_order_n_447fed_idx'), models.Index(fields=['created_at'], name='store_analy_created_316369_idx')],
            },
        ),
    ]
