# Generated by Django 5.2.1 on 2025-06-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0003_alter_storeanalysis_checkout_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeanalysis',
            name='average_basket',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='میانگین سبد خرید'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='avg_visit_time',
            field=models.IntegerField(default=0, verbose_name='میانگین زمان حضور (دقیقه)'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='blind_spots',
            field=models.JSONField(default=list, verbose_name='نقاط کور'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='customer_feedback',
            field=models.JSONField(default=list, verbose_name='بازخوردهای مشتری'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='daily_customers',
            field=models.IntegerField(default=0, verbose_name='تعداد مشتری روزانه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ تخفیف'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='energy_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مصرف انرژی (کیلووات)'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='hot_cold_spots',
            field=models.JSONField(default=list, verbose_name='نقاط گرم/سرد'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='humidity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='رطوبت (%)'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='lighting_type',
            field=models.CharField(choices=[('natural', 'طبیعی'), ('artificial', 'مصنوعی'), ('mixed', 'ترکیبی')], default='artificial', max_length=100, verbose_name='نوع نورپردازی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='peak_hours',
            field=models.JSONField(default=list, verbose_name='ساعات پیک فروش'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='purchase_pattern',
            field=models.JSONField(default=dict, verbose_name='الگوی خرید'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='return_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ بازگشت کالا'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='sales_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حجم فروش روزانه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='satisfaction_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='امتیاز رضایت'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='seasonal_changes',
            field=models.JSONField(default=dict, verbose_name='تغییرات فصلی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='دمای محیط (سانتی\u200cگراد)'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='ventilation_type',
            field=models.CharField(default='', max_length=100, verbose_name='نوع تهویه'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='color_temperature',
            field=models.IntegerField(default=0, verbose_name='دمای رنگ (کلوین)'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='lighting_intensity',
            field=models.IntegerField(default=0, verbose_name='شدت نور (لوکس)'),
        ),
    ]
