# Generated by Django 4.2.23 on 2025-09-28 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0004_sitestats_systemsettings_supportticket_ticket_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('legal_agreement_accepted', models.BooleanField(default=False, verbose_name='تایید تعهدنامه')),
                ('legal_agreement_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید تعهدنامه')),
                ('newsletter_subscription', models.BooleanField(default=True, verbose_name='عضویت در خبرنامه')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای ایمیل')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='اعلان\u200cهای پیامک')),
                ('bio', models.TextField(blank=True, verbose_name='درباره من')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
                'indexes': [models.Index(fields=['user'], name='store_analy_user_id_f05d07_idx'), models.Index(fields=['legal_agreement_accepted'], name='store_analy_legal_a_feb461_idx'), models.Index(fields=['created_at'], name='store_analy_created_ebafe7_idx')],
            },
        ),
    ]
