# Generated by Django 5.2.1 on 2025-06-07 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0004_storeanalysis_average_basket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeanalysis',
            name='avg_customer_time',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='customer_traffic',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='description',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='email',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='layout_image',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='main_entrance',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='main_lighting',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='product_placement',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='special_areas',
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='منطقه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='brand_colors',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رنگ\u200cهای اصلی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='camera_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد دوربین'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='camera_coverage',
            field=models.TextField(blank=True, null=True, verbose_name='مناطق تحت پوشش دوربین'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='camera_locations',
            field=models.TextField(blank=True, null=True, verbose_name='موقعیت دوربین\u200cها'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='customer_movement_paths',
            field=models.TextField(blank=True, null=True, verbose_name='مسیر معمول حرکت مشتریان'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='customer_path_direction',
            field=models.CharField(blank=True, choices=[('clockwise', 'ساعتگرد'), ('counterclockwise', 'پادساعتگرد'), ('mixed', 'مختلط')], max_length=50, null=True, verbose_name='جهت حرکت مشتریان'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='customer_path_notes',
            field=models.TextField(blank=True, verbose_name='توضیحات تکمیلی مسیر'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='customer_path_type',
            field=models.JSONField(blank=True, null=True, verbose_name='نقاط کلیدی مسیر'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='customer_video_file',
            field=models.FileField(blank=True, null=True, upload_to='customer_videos/', verbose_name='ویدیوی مسیر مشتری'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='daily_sales',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='حجم فروش روزانه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='decorative_elements',
            field=models.TextField(blank=True, verbose_name='عناصر دکوراتیو'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='design_style',
            field=models.CharField(blank=True, choices=[('traditional', 'سنتی'), ('modern', 'مدرن'), ('minimal', 'خلوت'), ('busy', 'شلوغ'), ('simple', 'ساده'), ('bright', 'پرنور'), ('dim', 'کم\u200cنور')], max_length=50, null=True, verbose_name='سبک طراحی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='entrances',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد ورودی\u200cها'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='entrances_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد ورودی/خروجی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='entrances_desc',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح موقعیت ورودی/خروجی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='has_surveillance',
            field=models.BooleanField(default=False, verbose_name='دوربین نظارتی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='high_traffic_areas',
            field=models.TextField(blank=True, null=True, verbose_name='مناطق پرتردد'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='layout_restrictions',
            field=models.TextField(blank=True, verbose_name='محدودیت\u200cهای چیدمان'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='pos_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='نرم\u200cافزار صندوق'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='product_catalog',
            field=models.FileField(blank=True, null=True, upload_to='product_catalogs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='کاتالوگ محصولات'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='sales_file',
            field=models.FileField(blank=True, null=True, upload_to='sales_files/', verbose_name='فایل فروش'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='shelf_contents',
            field=models.TextField(blank=True, null=True, verbose_name='نوع محصولات هر قفسه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='shelf_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد قفسه اصلی'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='shelf_dimensions',
            field=models.TextField(blank=True, null=True, verbose_name='ابعاد تقریبی هر قفسه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_dimensions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ابعاد فروشگاه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_length',
            field=models.FloatField(blank=True, null=True, verbose_name='طول فروشگاه (متر)'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='موقعیت فروشگاه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_photos',
            field=models.FileField(blank=True, null=True, upload_to='store_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='عکس\u200cهای فروشگاه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_plan',
            field=models.FileField(blank=True, null=True, upload_to='store_plans/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'pdf', 'dwg'])], verbose_name='نقشه فروشگاه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض فروشگاه (متر)'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='top_products',
            field=models.TextField(blank=True, null=True, verbose_name='پرفروش\u200cترین محصولات'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='unused_area_reason',
            field=models.TextField(blank=True, verbose_name='دلیل بلااستفاده بودن'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='unused_area_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ منطقه بلااستفاده'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='unused_area_type',
            field=models.CharField(blank=True, choices=[('empty', 'منطقه خالی'), ('low_traffic', 'کم\u200cترافیک'), ('storage', 'انبار'), ('staff', 'فضای کارکنان'), ('other', 'سایر')], max_length=50, null=True, verbose_name='نوع منطقه بلااستفاده'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='unused_areas',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی مناطق بلااستفاده'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='unused_areas_desc',
            field=models.TextField(blank=True, verbose_name='توضیحات تکمیلی مناطق بلااستفاده'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='video_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ضبط ویدیو'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان ویدیو (ثانیه)'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='video_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت ضبط ویدیو'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='checkout_location',
            field=models.TextField(blank=True, null=True, verbose_name='محل صندوق\u200cهای پرداخت'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='peak_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ساعات پیک فروش'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='product_categories',
            field=models.JSONField(blank=True, null=True, verbose_name='دسته\u200cبندی محصولات'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='store_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ فروشگاه (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='store_type',
            field=models.CharField(choices=[('supermarket', 'سوپرمارکت'), ('clothing', 'فروشگاه پوشاک'), ('appliance', 'لوازم خانگی'), ('bookstore', 'کتاب\u200cفروشی'), ('pharmacy', 'داروخانه'), ('other', 'سایر')], max_length=50, verbose_name='نوع فروشگاه'),
        ),
        migrations.CreateModel(
            name='StoreAnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('recommendations', models.TextField(verbose_name='توصیه\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='store_analysis.storeanalysis')),
            ],
        ),
    ]
