# Generated by Django 5.2.1 on 2025-06-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0006_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='امتیاز کلی')),
                ('layout_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='امتیاز چیدمان')),
                ('traffic_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='امتیاز ترافیک')),
                ('design_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='امتیاز طراحی')),
                ('sales_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='امتیاز فروش')),
                ('layout_analysis', models.TextField(verbose_name='تحلیل چیدمان')),
                ('traffic_analysis', models.TextField(verbose_name='تحلیل ترافیک')),
                ('design_analysis', models.TextField(verbose_name='تحلیل طراحی')),
                ('sales_analysis', models.TextField(verbose_name='تحلیل فروش')),
                ('overall_analysis', models.TextField(verbose_name='تحلیل کلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='store_analysis.storeanalysis')),
            ],
            options={
                'verbose_name': 'نتیجه تحلیل',
                'verbose_name_plural': 'نتایج تحلیل',
                'ordering': ['-created_at'],
            },
        ),
    ]
