# Generated by Django 4.2.23 on 2025-09-28 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0007_create_sitestats_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConsultantService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرویس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سرویس مشاوره هوش مصنوعی',
                'verbose_name_plural': 'سرویس\u200cهای مشاوره هوش مصنوعی',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('features', models.TextField(verbose_name='ویژگی\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پلن قیمت\u200cگذاری',
                'verbose_name_plural': 'پلن\u200cهای قیمت\u200cگذاری',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('transaction_type', models.CharField(max_length=20, verbose_name='نوع تراکنش')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='StoreTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_traffic', models.CharField(default='medium', max_length=20, verbose_name='ترافیک مشتری')),
                ('peak_hours', models.CharField(blank=True, max_length=100, verbose_name='ساعات پیک')),
                ('customer_movement_paths', models.CharField(default='mixed', max_length=100, verbose_name='مسیرهای حرکت مشتری')),
                ('high_traffic_areas', models.CharField(blank=True, max_length=200, verbose_name='مناطق پرترافیک')),
                ('customer_path_notes', models.CharField(blank=True, max_length=200, verbose_name='یادداشت\u200cهای مسیر')),
                ('has_customer_video', models.BooleanField(default=False, verbose_name='دارای ویدیو مشتری')),
                ('video_duration', models.IntegerField(blank=True, null=True, verbose_name='مدت ویدیو')),
                ('video_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ویدیو')),
                ('video_time', models.TimeField(blank=True, null=True, verbose_name='زمان ویدیو')),
                ('store_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.storebasicinfo', verbose_name='اطلاعات فروشگاه')),
            ],
            options={
                'verbose_name': 'ترافیک فروشگاه',
                'verbose_name_plural': 'ترافیک\u200cهای فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='StoreSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_surveillance', models.BooleanField(default=False, verbose_name='دارای نظارت')),
                ('camera_count', models.IntegerField(blank=True, null=True, verbose_name='تعداد دوربین')),
                ('camera_locations', models.CharField(blank=True, max_length=200, verbose_name='محل دوربین\u200cها')),
                ('camera_coverage', models.CharField(blank=True, max_length=200, verbose_name='پوشش دوربین')),
                ('recording_quality', models.CharField(default='medium', max_length=20, verbose_name='کیفیت ضبط')),
                ('storage_duration', models.IntegerField(default=30, verbose_name='مدت ذخیره')),
                ('store_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.storebasicinfo', verbose_name='اطلاعات فروشگاه')),
            ],
            options={
                'verbose_name': 'نظارت فروشگاه',
                'verbose_name_plural': 'نظارت\u200cهای فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='StoreProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_categories', models.CharField(blank=True, max_length=200, verbose_name='دسته\u200cبندی محصولات')),
                ('main_products', models.TextField(blank=True, verbose_name='محصولات اصلی')),
                ('seasonal_products', models.TextField(blank=True, verbose_name='محصولات فصلی')),
                ('product_display_method', models.CharField(blank=True, max_length=100, verbose_name='روش نمایش محصولات')),
                ('store_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.storebasicinfo', verbose_name='اطلاعات فروشگاه')),
            ],
            options={
                'verbose_name': 'محصولات فروشگاه',
                'verbose_name_plural': 'محصولات فروشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='StoreLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrances', models.IntegerField(default=1, verbose_name='تعداد ورودی')),
                ('exits', models.IntegerField(default=1, verbose_name='تعداد خروجی')),
                ('checkout_location', models.CharField(max_length=200, verbose_name='محل صندوق')),
                ('unused_area_type', models.CharField(max_length=50, verbose_name='نوع فضای خالی')),
                ('unused_area_size', models.IntegerField(default=0, verbose_name='اندازه فضای خالی')),
                ('unused_area_reason', models.TextField(blank=True, verbose_name='دلیل فضای خالی')),
                ('unused_areas', models.TextField(blank=True, verbose_name='فضاهای خالی')),
                ('layout_restrictions', models.TextField(blank=True, verbose_name='محدودیت\u200cهای چیدمان')),
                ('store_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.storebasicinfo', verbose_name='اطلاعات فروشگاه')),
            ],
            options={
                'verbose_name': 'چیدمان فروشگاه',
                'verbose_name_plural': 'چیدمان\u200cهای فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='StoreDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_style', models.CharField(default='modern', max_length=50, verbose_name='سبک طراحی')),
                ('brand_colors', models.CharField(blank=True, max_length=200, verbose_name='رنگ\u200cهای برند')),
                ('decorative_elements', models.CharField(blank=True, max_length=200, verbose_name='عناصر تزئینی')),
                ('main_lighting', models.CharField(default='artificial', max_length=50, verbose_name='نورپردازی اصلی')),
                ('lighting_intensity', models.CharField(default='medium', max_length=20, verbose_name='شدت نور')),
                ('color_temperature', models.CharField(default='neutral', max_length=20, verbose_name='دمای رنگ')),
                ('store_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.storebasicinfo', verbose_name='اطلاعات فروشگاه')),
            ],
            options={
                'verbose_name': 'طراحی فروشگاه',
                'verbose_name_plural': 'طراحی\u200cهای فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_analysis_data', models.JSONField(default=dict, verbose_name='داده\u200cهای تحلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'درخواست تحلیل',
                'verbose_name_plural': 'درخواست\u200cهای تحلیل',
            },
        ),
        migrations.CreateModel(
            name='AIConsultantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه جلسه')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.aiconsultantservice', verbose_name='سرویس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جلسه مشاوره هوش مصنوعی',
                'verbose_name_plural': 'جلسات مشاوره هوش مصنوعی',
            },
        ),
        migrations.CreateModel(
            name='AIConsultantQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='متن سوال')),
                ('answer_text', models.TextField(blank=True, verbose_name='متن پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.aiconsultantservice', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'سوال مشاوره هوش مصنوعی',
                'verbose_name_plural': 'سوالات مشاوره هوش مصنوعی',
            },
        ),
        migrations.CreateModel(
            name='AIConsultantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.aiconsultantsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'پرداخت مشاوره هوش مصنوعی',
                'verbose_name_plural': 'پرداخت\u200cهای مشاوره هوش مصنوعی',
            },
        ),
    ]
