# Generated by Django 5.2.1 on 2025-06-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0007_storeanalysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین'), ('wallet', 'کیف پول')], default='online', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
