# Generated by Django 5.2.1 on 2025-06-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0008_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeanalysis',
            name='has_customer_video',
            field=models.BooleanField(default=False, verbose_name='ویدیوی مسیر مشتری'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='camera_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد دوربین\u200cها'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='camera_coverage',
            field=models.TextField(blank=True, null=True, verbose_name='مناطق تحت پوشش'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='customer_movement_paths',
            field=models.CharField(choices=[('clockwise', 'ساعتگرد'), ('counterclockwise', 'پادساعتگرد'), ('mixed', 'مختلط'), ('random', 'تصادفی')], default='mixed', max_length=20, verbose_name='مسیر معمول حرکت مشتریان'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='customer_path_notes',
            field=models.TextField(verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان ویدیو'),
        ),
    ]
