# Generated by Django 5.2.1 on 2025-06-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0009_storeanalysis_has_customer_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeanalysis',
            name='unused_area_reason',
            field=models.TextField(default='', verbose_name='دلیل بلااستفاده بودن'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='unused_area_size',
            field=models.PositiveIntegerField(default=0, verbose_name='متراژ منطقه بلااستفاده'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='unused_area_type',
            field=models.CharField(choices=[('empty', 'منطقه خالی'), ('low_traffic', 'کم\u200cترافیک'), ('storage', 'انبار'), ('staff', 'فضای کارکنان'), ('other', 'سایر')], default='empty', max_length=20, verbose_name='نوع منطقه بلااستفاده'),
        ),
    ]
