# Generated by Django 5.1.6 on 2025-08-03 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0010_alter_storeanalysis_unused_area_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='کلید کش')),
                ('value', models.JSONField(verbose_name='مقدار کش')),
                ('cache_type', models.CharField(choices=[('analysis_results', 'نتایج تحلیل'), ('user_analyses', 'تحلیل\u200cهای کاربر'), ('statistics', 'آمار'), ('api_response', 'پاسخ API')], max_length=50, verbose_name='نوع کش')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'کش',
                'verbose_name_plural': 'کش\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='store_length',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='store_width',
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['user', '-created_at'], name='store_analy_user_id_7ce065_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['status', '-created_at'], name='store_analy_status_cf7331_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['user', 'status'], name='store_analy_user_id_f44dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['store_type', 'status'], name='store_analy_store_t_38ffc2_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['created_at'], name='store_analy_created_66b632_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['store_name'], name='store_analy_store_n_b47c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['city', 'area'], name='store_analy_city_bdf9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['has_surveillance'], name='store_analy_has_sur_e4dc74_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['has_customer_video'], name='store_analy_has_cus_d29bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['store_size'], name='store_analy_store_s_3f3394_idx'),
        ),
        migrations.AddIndex(
            model_name='cache',
            index=models.Index(fields=['key'], name='store_analy_key_537682_idx'),
        ),
        migrations.AddIndex(
            model_name='cache',
            index=models.Index(fields=['cache_type'], name='store_analy_cache_t_54643c_idx'),
        ),
        migrations.AddIndex(
            model_name='cache',
            index=models.Index(fields=['expires_at'], name='store_analy_expires_6cf26c_idx'),
        ),
    ]
