# Generated by Django 5.2.1 on 2025-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0011_cache_remove_storeanalysis_store_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeanalysis',
            name='sales_volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='حجم فروش روزانه'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='unused_area_type',
            field=models.CharField(blank=True, choices=[('empty', 'منطقه خالی'), ('low_traffic', 'کم\u200cترافیک'), ('storage', 'انبار'), ('staff', 'فضای کارکنان'), ('other', 'سایر')], default='empty', max_length=20, null=True, verbose_name='نوع منطقه بلااستفاده'),
        ),
    ]
