# Generated by Django 5.2.1 on 2025-08-10 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0012_alter_storeanalysis_sales_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='store_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store_analysis.storeanalysis', verbose_name='تحلیل فروشگاه'),
        ),
    ]
