# Generated by Django 5.2.1 on 2025-08-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0013_payment_store_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('summary', models.TextField(verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='متن کامل مقاله')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده/مترجم')),
                ('source_url', models.URLField(blank=True, verbose_name='لینک منبع اصلی')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='برچسب\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مقاله ویژه')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='تصویر مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مقاله',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مقاله',
            },
        ),
        migrations.RemoveField(
            model_name='storeanalysisdetail',
            name='store_analysis',
        ),
        migrations.RemoveIndex(
            model_name='storeanalysis',
            name='store_analy_user_id_7ce065_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeanalysis',
            name='store_analy_status_cf7331_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeanalysis',
            name='store_analy_user_id_f44dd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeanalysis',
            name='store_analy_store_t_38ffc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeanalysis',
            name='store_analy_created_66b632_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeanalysis',
            name='store_analy_store_n_b47c7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeanalysis',
            name='store_analy_city_bdf9f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeanalysis',
            name='store_analy_has_sur_e4dc74_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeanalysis',
            name='store_analy_has_cus_d29bf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeanalysis',
            name='store_analy_store_s_3f3394_idx',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='average_basket',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='avg_visit_time',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='blind_spots',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='color_temperature',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='customer_feedback',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='customer_path_direction',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='customer_path_type',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='daily_customers',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='daily_sales',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='energy_consumption',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='entrances_count',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='entrances_desc',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='has_customer_video',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='hot_cold_spots',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='lighting_intensity',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='lighting_type',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='purchase_pattern',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='return_rate',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='satisfaction_score',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='seasonal_changes',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='unused_areas_desc',
        ),
        migrations.RemoveField(
            model_name='storeanalysis',
            name='ventilation_type',
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='customer_path_notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='video_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساع�� ضبط ویدیو'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='store_analysis.articlecategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.DeleteModel(
            name='StoreAnalysisDetail',
        ),
    ]
