# Generated by Django 5.2.1 on 2025-08-12 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0014_article_articlecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='توصیه\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('store_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='store_analysis.storeanalysis', verbose_name='تحلیل فروشگاه')),
            ],
            options={
                'verbose_name': 'جزئیات تحلیل فروشگاه',
                'verbose_name_plural': 'جزئیات تحلیل\u200cهای فروشگاه',
                'ordering': ['-created_at'],
            },
        ),
    ]
