# Generated by Django 5.2.1 on 2025-08-14 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0015_storeanalysisdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeanalysis',
            name='video_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت ضبط ویدیو'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['user', 'status'], name='store_analy_user_id_f44dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['store_type', 'city'], name='store_analy_store_t_183d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['created_at'], name='store_analy_created_66b632_idx'),
        ),
    ]
