# Generated by Django 5.2.1 on 2025-08-16 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0017_storebasicinfo_storedesign_storelayout_storeproducts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebasicinfo',
            name='establishment_year',
            field=models.PositiveIntegerField(blank=True, help_text='سال تاسیس فروشگاه (1300 تا 1450)', null=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1450)], verbose_name='سال تاسیس'),
        ),
    ]
