# Generated by Django 5.2.1 on 2025-08-19 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0018_storebasicinfo_establishment_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeanalysis',
            name='analysis_data',
            field=models.JSONField(blank=True, help_text='داده\u200cهای ارسالی از فرم', null=True, verbose_name='داده\u200cهای تحلیل'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('quick_free', 'تحلیل رایگان سریع'), ('comprehensive', 'تحلیل جامع'), ('ai_enhanced', 'تحلیل هوشمند')], default='quick_free', max_length=20, verbose_name='نوع تحلیل'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='preliminary_analysis',
            field=models.TextField(blank=True, help_text='تحلیل اولیه که بلافاصله پس از پرداخت نمایش داده می\u200cشود', null=True, verbose_name='پیش\u200cتحلیل'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام فروشگاه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اندازه فروشگاه'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='store_type',
            field=models.CharField(blank=True, choices=[('supermarket', 'سوپرمارکت'), ('hypermarket', 'هایپرمارکت'), ('clothing', 'فروشگاه پوشاک'), ('appliance', 'لوازم خانگی'), ('bookstore', 'کتاب\u200cفروشی'), ('pharmacy', 'داروخانه'), ('electronics', 'الکترونیک'), ('jewelry', 'جواهرات'), ('sports', 'ورزشی'), ('beauty', 'آرایشی و بهداشتی'), ('other', 'سایر')], max_length=50, null=True, verbose_name='نوع فروشگاه'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('preliminary_completed', 'پیش\u200cتحلیل تکمیل شده'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=25, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='storeanalysis',
            index=models.Index(fields=['analysis_type'], name='store_analy_analysi_048c92_idx'),
        ),
    ]
