# Generated by Django 5.1.6 on 2025-08-30 20:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0019_storeanalysis_analysis_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('plan_type', models.CharField(choices=[('one_time', 'تحلیل یکباره'), ('monthly', 'پلن ماهیانه'), ('yearly', 'پلن سالیانه')], max_length=20, verbose_name='نوع پلن')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت اصلی')),
                ('discount_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('features', models.JSONField(default=list, verbose_name='ویژگی\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پلن قیمت\u200cگذاری',
                'verbose_name_plural': 'پلن\u200cهای قیمت\u200cگذاری',
            },
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=300, verbose_name='زیرعنوان')),
                ('discount_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('background_color', models.CharField(default='#FF6B6B', max_length=7, verbose_name='رنگ پس\u200cزمینه')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='رنگ متن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('max_uses', models.IntegerField(default=1, verbose_name='حداکثر استفاده')),
                ('used_count', models.IntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_from', models.DateTimeField(verbose_name='اعتبار از')),
                ('valid_until', models.DateTimeField(verbose_name='اعتبار تا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه سفارش')),
                ('original_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ اصلی')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ نهایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='روش پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_analysis.discountcode', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.pricingplan', verbose_name='پلن انتخاب شده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_analysis_data', models.JSONField(verbose_name='داده\u200cهای تحلیل فروشگاه')),
                ('initial_analysis', models.TextField(blank=True, verbose_name='تحلیل اولیه')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='تحلیل هوش مصنوعی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پردازش'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('estimated_completion', models.DateTimeField(blank=True, null=True, verbose_name='زمان تخمینی تکمیل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'درخواست تحلیل',
                'verbose_name_plural': 'درخواست\u200cهای تحلیل',
            },
        ),
    ]
