# Generated by Django 5.1.6 on 2025-08-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0020_pricingplan_promotionalbanner_discountcode_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalbanner',
            name='discount_text',
            field=models.CharField(default='تخفیف', max_length=100, verbose_name='متن تخفیف'),
        ),
    ]
