# Generated by Django 4.2.23 on 2025-09-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0022_analysisrequest_ai_analysis_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeanalysis',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='store_analysis.order', verbose_name='سفارش'),
        ),
    ]
