# Generated by Django 4.2.23 on 2025-09-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0023_storeanalysis_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_analysis.pricingplan', verbose_name='پلن انتخاب شده'),
        ),
    ]
