# Generated by Django 4.2.23 on 2025-09-12 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0025_alter_storeanalysis_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConsultantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه جلسه')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی شده'), ('completed', 'تکمیل شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('free_questions_used', models.PositiveIntegerField(default=0, verbose_name='سوالات رایگان استفاده شده')),
                ('paid_questions_used', models.PositiveIntegerField(default=0, verbose_name='سوالات پولی استفاده شده')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('store_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.storeanalysis', verbose_name='تحلیل فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جلسه مشاوره هوش مصنوعی',
                'verbose_name_plural': 'جلسات مشاوره هوش مصنوعی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConsultantQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
                ('is_answered', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
                ('is_free', models.BooleanField(default=True, verbose_name='رایگان')),
                ('response_time', models.DurationField(blank=True, null=True, verbose_name='زمان پاسخ')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='store_analysis.aiconsultantsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'سوال مشاوره',
                'verbose_name_plural': 'سوالات مشاوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConsultantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('amount', models.PositiveIntegerField(default=200000, verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش')),
                ('payment_gateway', models.CharField(default='zarinpal', max_length=50, verbose_name='درگاه پرداخت')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.aiconsultantsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'پرداخت مشاوره',
                'verbose_name_plural': 'پرداخت\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
    ]
