# Generated by Django 4.2.23 on 2025-09-15 21:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0026_aiconsultantsession_aiconsultantquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='max_uses',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت'), ('seasonal', 'فصلی'), ('event', 'مناسبتی')], default='percentage', max_length=20, verbose_name='نوع تخفیف'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='event_type',
            field=models.CharField(blank=True, choices=[('opening', 'افتتاحیه'), ('spring', 'بهار'), ('summer', 'تابستان'), ('autumn', 'پاییز'), ('winter', 'زمستان'), ('nowruz', 'نوروز'), ('yalda', 'شب یلدا'), ('ramadan', 'رمضان'), ('black_friday', 'جمعه سیاه'), ('new_year', 'سال نو')], max_length=20, null=True, verbose_name='نوع مناسبت'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='مبلغ ثابت'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='max_usage',
            field=models.PositiveIntegerField(default=100, verbose_name='حداکثر استفاده'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='percentage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(70)], verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('verification_code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاییدیه ایمیل',
                'verbose_name_plural': 'تاییدیه\u200cهای ایمیل',
                'ordering': ['-created_at'],
            },
        ),
    ]
