# Generated by Django 4.2.23 on 2025-09-15 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0027_remove_discountcode_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(default='fas fa-question-circle', max_length=50, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی سوالات متداول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای سوالات متداول',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('ticket_id', models.CharField(max_length=20, unique=True, verbose_name='شناسه تیکت')),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('technical', 'فنی'), ('billing', 'پرداخت'), ('feature_request', 'درخواست ویژگی'), ('bug_report', 'گزارش باگ'), ('account', 'حساب کاربری')], default='general', max_length=20, verbose_name='دسته\u200cبندی')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('waiting_user', 'در انتظار کاربر'), ('resolved', 'حل شده'), ('closed', 'بسته')], default='open', max_length=20, verbose_name='وضعیت')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='پیوست\u200cها')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cها')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('technical', 'فنی'), ('billing', 'پرداخت'), ('feature_request', 'درخواست ویژگی'), ('bug_report', 'گزارش باگ'), ('account', 'حساب کاربری')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'قالب پاسخ',
                'verbose_name_plural': 'قالب\u200cهای پاسخ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('message_type', models.CharField(choices=[('user', 'کاربر'), ('admin', 'مدیر'), ('system', 'سیستم')], default='user', max_length=10, verbose_name='نوع پیام')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('is_internal', models.BooleanField(default=False, verbose_name='داخلی')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='پیوست\u200cها')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store_analysis.supportticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('question', models.CharField(max_length=200, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('keywords', models.TextField(blank=True, help_text='کلمات کلیدی جدا شده با کاما', verbose_name='کلمات کلیدی')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analysis.faqcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['category__order', 'order', 'question'],
            },
        ),
    ]
