# Generated by Django 4.2.23 on 2025-10-01 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0036_remove_faqservice_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ اصلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_analysis.servicepackage', verbose_name='پکیج'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای تحلیل'),
        ),
        migrations.AddField(
            model_name='storeanalysis',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_analysis.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='store_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس فروشگاه'),
        ),
    ]
