# Generated by Django 4.2.23 on 2025-10-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0037_order_original_amount_order_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeanalysis',
            name='preliminary_analysis',
            field=models.TextField(blank=True, verbose_name='تحلیل اولیه'),
        ),
    ]
