# Generated by Django 4.2.23 on 2025-10-04 08:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0041_phonebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوای تبلیغاتی')),
                ('image_url', models.URLField(blank=True, verbose_name='آدرس تصویر')),
                ('link_url', models.URLField(blank=True, verbose_name='لینک تبلیغاتی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 11, 3, 8, 53, 35, 712003, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان')),
                ('priority', models.IntegerField(default=1, verbose_name='اولویت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
