# Generated by Django 4.2.23 on 2025-10-07 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0049_add_store_images_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeanalysis',
            name='priority',
            field=models.CharField(default='medium', max_length=10, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 0, 33, 35, 894750, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
