# Generated by Django 4.2.23 on 2025-10-07 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0051_add_order_number_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 4, 29, 46, 133385, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
