# Generated by Django 4.2.23 on 2025-10-08 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0052_alter_promotionalbanner_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='online', max_length=50, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 22, 34, 56, 303705, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
