# Generated by Django 4.2.23 on 2025-10-09 21:54

from django.db import migrations


def create_usersubscription_table(apps, schema_editor):
    """Create UserSubscription table using raw SQL"""
    if schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS store_analysis_usersubscription (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                service_package_id INTEGER NOT NULL,
                start_date DATETIME NOT NULL,
                end_date DATETIME NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        """)
    elif schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS store_analysis_usersubscription (
                id SERIAL PRIMARY KEY,
                user_id INTEGER NOT NULL,
                service_package_id INTEGER NOT NULL,
                start_date TIMESTAMP WITH TIME ZONE NOT NULL,
                end_date TIMESTAMP WITH TIME ZONE NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT true,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
            );
        """)


def reverse_create_usersubscription_table(apps, schema_editor):
    """Drop UserSubscription table"""
    schema_editor.execute("DROP TABLE IF EXISTS store_analysis_usersubscription;")


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0060_fix_usersubscription_table'),
    ]

    operations = [
        migrations.RunPython(
            create_usersubscription_table,
            reverse_create_usersubscription_table,
        ),
    ]
