# Generated by Django 4.2.23 on 2025-10-10 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0062_fix_storeanalysis_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 0, 45, 51, 316032, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
