# Generated by Django 4.2.23 on 2025-10-10 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0066_discountnotification_delete_systemsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='discountnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اطلاعیه تخفیف', 'verbose_name_plural': 'اطلاعیه\u200cهای تخفیف'},
        ),
        migrations.RemoveField(
            model_name='discountnotification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='discountnotification',
            name='key',
        ),
        migrations.RemoveField(
            model_name='discountnotification',
            name='value',
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 19, 59, 53, 317909, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
