# Generated by Django 4.2.23 on 2025-10-11 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0071_chatsession_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 10, 20, 44, 46, 106318, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
