# Generated by Django 4.2.23 on 2025-10-13 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0072_alter_promotionalbanner_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 12, 19, 40, 29, 556049, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(help_text='شماره موبایل برای پرداخت و ارسال پیامک الزامی است', max_length=11, verbose_name='شماره موبایل'),
        ),
    ]
