# Generated by Django 4.2.23 on 2025-10-15 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0075_fix_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد مرجع درگاه'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 21, 5, 5, 241826, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
