# Generated by Django 4.2.23 on 2025-10-15 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0076_add_authority_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'کاربر'), ('admin', 'ادمین'), ('system', 'سیستم')], default='user', max_length=10, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 23, 27, 10, 479194, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
