# Generated by Django 4.2.23 on 2025-10-17 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0078_remove_wallettransaction_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 19, 6, 3, 114635, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
