# Generated by Django 4.2.23 on 2025-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0082_add_critical_missing_fields'),
    ]

    operations = [
        # authority field already added in an earlier migration (0076); skip here.
        
        # employee_count and lighting_score already exist in earlier migration (0004); skip here.
    ]
