# Generated by Django 4.2.23 on 2025-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0082_add_critical_missing_fields'),
    ]

    operations = [
        # اضافه کردن فیلد authority به Payment
        migrations.AddField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد مرجع درگاه'),
        ),
        
        # اضافه کردن فیلد employee_count به StoreBasicInfo
        migrations.AddField(
            model_name='storebasicinfo',
            name='employee_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد کارکنان'),
        ),
        
        # اضافه کردن فیلد lighting_score به StoreAnalysisResult
        migrations.AddField(
            model_name='storeanalysisresult',
            name='lighting_score',
            field=models.FloatField(default=0, verbose_name='امتیاز نورپردازی'),
        ),
    ]
