# Generated by Django 4.2.23 on 2025-10-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0084_add_performance_indexes'),
    ]

    operations = [
        # اضافه کردن فیلد analysis_id به StoreAnalysisResult
        migrations.AddField(
            model_name='storeanalysisresult',
            name='analysis_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تحلیل'),
        ),
    ]
