# Generated by Django 4.2.23 on 2025-10-18 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0090_alter_promotionalbanner_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 20, 49, 2, 720980, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
