# Generated by Django 4.2.23 on 2025-10-18 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0092_add_servicepackage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 21, 4, 21, 539940, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
