# Generated by Django 4.2.23 on 2025-10-19 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0103_add_storeanalysis_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 18, 21, 40, 37, 76574, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
    ]
