# Generated by Django 4.2.23 on 2025-10-29 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0111_alter_promotionalbanner_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 28, 4, 23, 35, 24209, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پایان'),
        ),
        migrations.CreateModel(
            name='FreeUsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='نام کاربری')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='شماره موبایل')),
                ('ip_address', models.CharField(db_index=True, max_length=255, verbose_name='آدرس IP')),
                ('analysis_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه تحلیل')),
                ('store_name', models.CharField(blank=True, max_length=200, verbose_name='نام فروشگاه')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='مسدود شده')),
                ('block_reason', models.TextField(blank=True, verbose_name='دلیل مسدودیت')),
                ('first_usage', models.DateTimeField(auto_now_add=True, verbose_name='اولین استفاده')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='آخرین بررسی')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('additional_info', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
            ],
            options={
                'verbose_name': 'ردیابی استفاده رایگان',
                'verbose_name_plural': 'ردیابی استفاده رایگان',
                'ordering': ['-first_usage'],
                'indexes': [models.Index(fields=['username'], name='store_analy_usernam_dcf921_idx'), models.Index(fields=['email'], name='store_analy_email_bb753e_idx'), models.Index(fields=['phone'], name='store_analy_phone_ed9c46_idx'), models.Index(fields=['ip_address'], name='store_analy_ip_addr_1381a1_idx'), models.Index(fields=['is_blocked'], name='store_analy_is_bloc_75ac2f_idx'), models.Index(fields=['first_usage'], name='store_analy_first_u_f23a1e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='freeusagetracking',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username_free_usage'),
        ),
    ]
