# Generated by Django 4.2.23 on 2025-11-01 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_analysis', '0114_alter_promotionalbanner_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField(default=30, verbose_name='درصد تخفیف')),
                ('analysis_completed_at', models.DateTimeField(verbose_name='تاریخ تکمیل تحلیل')),
                ('reminder_date', models.DateTimeField(verbose_name='تاریخ یادآوری')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال ایمیل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارسال'), ('scheduled', 'زمان\u200cبندی شده'), ('sent', 'ارسال شده'), ('expired', 'منقضی شده'), ('used', 'استفاده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('email_sent', models.BooleanField(default=False, verbose_name='ایمیل ارسال شده')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reminders', to='store_analysis.storeanalysis', verbose_name='تحلیل')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_analysis.discountcode', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'یادآوری بازبینی',
                'verbose_name_plural': 'یادآوری\u200cهای بازبینی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['analysis'], name='store_analy_analysi_c7a6e4_idx'), models.Index(fields=['user'], name='store_analy_user_id_7ffa71_idx'), models.Index(fields=['status'], name='store_analy_status_1919f2_idx'), models.Index(fields=['reminder_date'], name='store_analy_reminde_c280c5_idx'), models.Index(fields=['email_sent'], name='store_analy_email_s_effc63_idx')],
            },
        ),
    ]
