# Generated by Django 4.2.23 on 2025-11-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0117_fix_userprofile_address_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='اگر True باشد، فقط برای ادمین\u200cها قابل مشاهده است', verbose_name='پیام داخلی'),
        ),
    ]
