# Generated by Django 4.2.23 on 2025-11-17 20:04
# Modified to safely handle missing columns

from django.db import migrations


def remove_contact_fields_safe(apps, schema_editor):
    """
    Safely remove contact_email and contact_phone fields from StoreAnalysis if they exist
    Works with both PostgreSQL (Liara) and SQLite (local dev)
    """
    db_alias = schema_editor.connection.alias
    vendor = schema_editor.connection.vendor
    
    # Check if columns exist
    contact_email_exists = False
    contact_phone_exists = False
    
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            # PostgreSQL uses information_schema
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='store_analysis_storeanalysis' 
                AND column_name='contact_email'
            """)
            contact_email_exists = cursor.fetchone() is not None
            
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='store_analysis_storeanalysis' 
                AND column_name='contact_phone'
            """)
            contact_phone_exists = cursor.fetchone() is not None
        elif vendor == 'sqlite':
            # SQLite uses PRAGMA table_info
            cursor.execute("PRAGMA table_info(store_analysis_storeanalysis)")
            columns = [row[1] for row in cursor.fetchall()]
            contact_email_exists = 'contact_email' in columns
            contact_phone_exists = 'contact_phone' in columns
    
    # Remove columns if they exist
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            if contact_email_exists:
                cursor.execute("ALTER TABLE store_analysis_storeanalysis DROP COLUMN IF EXISTS contact_email;")
                print("✅ Removed contact_email column")
            else:
                print("ℹ️ contact_email column does not exist, skipping...")
            
            if contact_phone_exists:
                cursor.execute("ALTER TABLE store_analysis_storeanalysis DROP COLUMN IF EXISTS contact_phone;")
                print("✅ Removed contact_phone column")
            else:
                print("ℹ️ contact_phone column does not exist, skipping...")
        elif vendor == 'sqlite':
            # SQLite doesn't support DROP COLUMN easily, skip for now
            if contact_email_exists or contact_phone_exists:
                print("⚠️ SQLite doesn't support DROP COLUMN - columns will remain in database")
            pass


def add_contact_fields_safe(apps, schema_editor):
    """
    Reverse migration - add contact fields back if needed (for rollback)
    """
    db_alias = schema_editor.connection.alias
    vendor = schema_editor.connection.vendor
    
    # Check if columns exist
    contact_email_exists = False
    contact_phone_exists = False
    
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='store_analysis_storeanalysis' 
                AND column_name='contact_email'
            """)
            contact_email_exists = cursor.fetchone() is not None
            
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='store_analysis_storeanalysis' 
                AND column_name='contact_phone'
            """)
            contact_phone_exists = cursor.fetchone() is not None
    
    # Add columns back if they don't exist (for rollback)
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            if not contact_email_exists:
                cursor.execute("""
                    ALTER TABLE store_analysis_storeanalysis 
                    ADD COLUMN contact_email VARCHAR(254);
                """)
            if not contact_phone_exists:
                cursor.execute("""
                    ALTER TABLE store_analysis_storeanalysis 
                    ADD COLUMN contact_phone VARCHAR(20);
                """)
        elif vendor == 'sqlite':
            # SQLite doesn't support adding columns back easily
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('store_analysis', '0118_ticketmessage_is_internal'),
    ]

    operations = [
        migrations.RunPython(remove_contact_fields_safe, add_contact_fields_safe),
    ]
